### PR TITLE
Replaced activationEvents with activationCommands

### LINKED ISSUE #7: Package.getActivationCommands is deprecated.
Use `activationCommands` instead of `activationEvents` in your package.json
Commands should be grouped by selector as follows:
```json
  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
```
```
Package.getActivationCommands (C:\Users\Benjamin\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:790:9)
Package.hasActivationCommands (C:\Users\Benjamin\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:715:20)
<unknown> (C:\Users\Benjamin\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:169:24)
Package.measure (C:\Users\Benjamin\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:147:15)
```

### LINKED ISSUE #9: Package.getActivationCommands is deprecated.
Use `activationCommands` instead of `activationEvents` in your package.json
Commands should be grouped by selector as follows:
```json
  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
```
```
Package.getActivationCommands (C:\Users\Benjamin\AppData\Local\atom\app-0.198.0\resources\app.asar\src\package.js:810:9)
Package.hasActivationCommands (C:\Users\Benjamin\AppData\Local\atom\app-0.198.0\resources\app.asar\src\package.js:735:20)
<unknown> (C:\Users\Benjamin\AppData\Local\atom\app-0.198.0\resources\app.asar\src\package.js:189:24)
Package.measure (C:\Users\Benjamin\AppData\Local\atom\app-0.198.0\resources\app.asar\src\package.js:167:15)
```

### PR DESCRIPTION
**Pull request by Fank**
Fixes #7
Fixes #9

### CODE REVIEW

**Comment by jfarmer** [comment]
Would love to see this merged so that little :warning: icon goes away. :smiley:

**Comment by Stanzilla** [comment]
@kevinsawicki seems to be on duty for those little cleanups, maybe he can help?

**Comment by kevinsawicki** [comment]
Thanks!

**Comment by kevinsawicki** [comment]
Published as `0.1.6`

**Pull request merged**
