### PR TITLE
Added linter as a package-deps - issue #16

### PR DESCRIPTION
**Pull request by gforge**

### CODE REVIEW

**Comment by Arcanemagus** [comment]
You'll also need to add `atom-package-deps` as [a dependency](https://github.com/AtomLinter/linter-stylelint/blob/v2.0.1/package.json#L35), and call its [`install()` function](https://github.com/AtomLinter/linter-stylelint/blob/v2.0.1/lib/index.js#L37) with the proper name.

**Comment by gforge** [comment]
@Arcanemagus Ok, a little more than I expected but I think it works now. At least it did work when I ran apm install in the folder and then restarted. Started using Atom yesterday #best_thing_2016 :-)

**Comment by Arcanemagus** [comment]
That should do it, thanks!

And welcome to the club :wink::tada:

**Comment by Arcanemagus** [comment]
Published in v1.0.2 :tada:

**Pull request merged**
